"""'add inventory items table'

Revision ID: c199340ac597
Revises: 1d9a002d7234
Create Date: 2026-02-04 18:42:26.189742

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "c199340ac597"
down_revision: str | None = "1d9a002d7234"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_items",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("food_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["ingredient_foods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["ingredient_units.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_items_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_items_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_items_household_id"), ["household_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inventory_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_items_household_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_items_group_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_items_created_at"))

    op.drop_table("inventory_items")
    # ### end Alembic commands ###
